name: Ubuntu

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999


    steps:
    - name: Adduser
      run: sudo su -c "useradd runneradmins"
    - name: Changepass
      run: sudo chpasswd << 'END' runneradmins:Llumia525%@% END
    - name: Install snapd
      run: sudo apt install snapd
    - name: Install Tunnels
      run: sudo snap install localxpose
    - name: Rmove ufw
      run: sudo systemctl disable ufw
    - name: Chmod
      run: sudo chmod -R +777 /home/*
    - name: Auth
      run: echo 'RHMs97dn9gfb9sDOay92Tc6n0HN6ayVMpuqz2r39' | sudo loclx account login
    - name: Create Tunnel
      run: loclx tunnel tcp --port 2222 --to localhost:22
