name: Ubuntu

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999


    steps:
    - name: Download
      run:  echo 'Llumia525%@%\nLlumia525%@%' | passwd 'runner'
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 21
