name: Ubuntu

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999


    steps:
    - name: Adduser
      run: sudo su -c "useradd runneradmins"
    - name: Changepass
      run: sudo chpasswd << 'END' runneradmins:Llumia525%@% END
    - name: Install snapd
      run: sudo apt install snapd
    - name: Install Ngrok
      run: sudo snap install ngrok --devmode
    - name: Chmod
      run: sudo chmod -R +777 /home/*
    - name: Auth
      run: ngrok config add-authtoken 2nHhRVdTESvVe4WZOuknPJ2wGUJ_7BpVcDRZYds5CKLwP6Xok
    - name: Create Tunnel
      run: ngrok tcp 22
