name: Ubuntu

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999


    steps:
    - name: Adduser
      run: sudo su -c "useradd runneradmins"
    - name: Changepass
      run: sudo chpasswd << 'END' runneradmins:Llumia525%@% END
    - name: Create Tunnel
      run: .\ngrok\ngrok.exe tcp 21
